### ISSUE TITLE
Pagination does not work anymore (It return only devices from first page)

### ISSUE THREAD

**Issue by dandys71** [nordmarin/gsmarena-api#11]
They've made some changes on their website, so now it only return devices from the first page. If you want to make it work again just **change function getNextPage in catalog.js** **from this:**
`const getNextPage = ($) => {
const nextPage = $('a.pages-next').attr('href');
    if (nextPage) {
        if (nextPage.indexOf('#') >= 0) {
            return false;
        }
        return nextPage.replace('.php', '');
    }
    return false;
};`

**to this:**
`const getNextPage = ($) => {
    const nextPage = $('a.prevnextbutton[title="Next page"]').attr('href');
    if (nextPage) {
        return nextPage.replace('.php', '');
    }
    return false;
};`

**Comment by nordmarin** [comment]
Yes, it really stopped working :(

Fixed it, thanks a lot for your help!
