### ISSUE TITLE
Api is not working because free account of heroku has been shut down

### ISSUE THREAD

**Issue by SiddharthMishra2703** [nordmarin/gsmarena-api#2]
This api is not working because free account of heroku are stopped working. So please make it live on some other platform.

**Comment by raleighlittles** [comment]
@nordmarin 

This is what we see when we go to the link: http://gsmarena-api.herokuapp.com/doc/

![image](https://user-images.githubusercontent.com/2137201/214925506-cd1ca31c-cfe5-4a1f-9426-7789cd6b6d10.png)

**Comment by nordmarin** [comment]
There was only swagger and was not intended for stable use. I hope for your understanding.
