### ISSUE TITLE
Filter by weight

### ISSUE THREAD

**Issue by mathieujobin** [nordmarin/gsmarena-api#9]
would it be easy to filter out any phones that weight above a certain weight?

I'd like a list of lite phone, and I have not found anything newer that the Xiaomi 11 Lite 5G

what a shame, right?

Thanks for working on an API client

**Comment by nordmarin** [comment]
Hello! If you want a filter by weight, it is not implemented, unfortunately.

**Comment by mathieujobin** [comment]
are you fetching this information already yet?

since they have a rate limiting pretty strict, should we store the data in the repo as cached data? 

if the data is there, then maybe I can add the filter.

**Comment by pranjalbajpai23** [comment]
how to get price of specific phone?

**Comment by mathieujobin** [comment]
I found another API that fetches the info I needed
Thanks
https://rapidapi.com/samehsilim/api/cellphones
